-- Your current Supabase table structure
CREATE TABLE public.shared_images (
  id bigint generated by default as identity not null,
  image_name text null,
  image_url text null,
  constraint shared_images_pkey primary key (id),
  constraint shared_images_id_key unique (id),
  constraint shared_images_image_url_key unique (image_url)
) TABLESPACE pg_default;

-- Note: This table is already created in Supabase.
-- This file is for documentation purposes only. 